-
  name: Install deps
  apt: name={{ item }} state=present
  with_items:
    - postgresql-server-dev-9.4
    - libpq-dev
    - ruby-dev

-
  name: copy PhantomJS installation file
  copy: src=install_phantomjs.sh mode=u+rwx dest=/tmp/install_phantomjs.sh

-
  name: Install PhantomJS
  command: ./install_phantomjs.sh chdir=/tmp

-
  name: Clone Prezento
  git: repo=https://github.com/Mezuro-labxp2016/prezento.git dest=/vagrant/src/prezento accept_hostkey=yes version=fix_setup force=yes

-
  name: prezento setup
  command: bin/setup chdir=/vagrant/src/prezento

-
  name: start prezento
  command: rails s -d -b 0.0.0.0
